### ISSUE TITLE
Question about MHumanEval

### ISSUE THREAD

**Issue by franciscoliu** [RLHF-V/RLHF-V#13]
Dear authors, thank you for sharing the code of this impressive work! I am just wondering if you have instructions of how to use MHumanEval benchmark as a evaluator? I saw the github presents multiple benchmarks but no MHumanEval. Or if you had already shown this in some external links, could you direct me to the link? Thank you in advance!

**Comment by if-noc** [comment]
Dear authors, I have been attempting at reproducing the results from experiments in your paper. However, I have trouble looking for the MHumanEval benchmark. I would greatly appreciate it if you could offer some details or external links of the dataset to me. Thank you for your time and assistance.
