### ISSUE TITLE
CUDA ordinal error within run_RLHFV.sh

### ISSUE THREAD

**Issue by rezacopol** [RLHF-V/RLHF-V#17]
Any idea what is wrong? 
using Cuda 12.2 and torch 2.3.0 and transformers 4.28.0

`
local:/mnt/task_runtime/RLHF-V/muffin# bash ./script/train/run_RLHFV.sh ./RLHFV_checkpoints/dpo_exp master RLHFV 1.1 $ref_model ./RLHF-V-Dataset RLHFV_SFT 2160 360 0.1 False True
Working Directory at /mnt/task_runtime/RLHF-V/muffin
Bash at /usr/bin/bash
Python at /miniconda/envs/muffin/bin/python
Tue Apr 30 23:50:16 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   37C    P0    67W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
master local_addr=local
ddpo weight is 1.1 beta is 0.1
pythonpath=:/mnt/task_runtime/RLHF-V/muffin
RUNNER=torchrun --nnodes=1 --nproc_per_node=8 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=local
Data config: ./RLHF-V-Dataset RLHFV_SFT
sft_output_dir=./RLHFV_checkpoints/dpo_exp/muffin_13b_DPO-RLHFV---beit3_large_patch16_448/checkpionts sft_logging_dir=./RLHFV_checkpoints/dpo_exp/muffin_13b_DPO-RLHFV---beit3_large_patch16_448/log
Load from ./RLHF-V_SFT_weight
W0430 23:50:23.074000 134467772659520 torch/distributed/run.py:757] 
W0430 23:50:23.074000 134467772659520 torch/distributed/run.py:757] *****************************************
W0430 23:50:23.074000 134467772659520 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0430 23:50:23.074000 134467772659520 torch/distributed/run.py:757] *****************************************
/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py:1356: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
DPO data: ./RLHF-V-Dataset RLHFV_SFT
[rank6]: Traceback (most recent call last):
[rank6]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank6]:     train()
[rank6]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank6]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank6]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank6]:     obj = dtype(**inputs)
[rank6]:   File "<string>", line 118, in __init__
[rank6]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank6]:     and (self.device.type != "cuda")
[rank6]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank6]:     return self._setup_devices
[rank6]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank6]:     cached = self.fget(obj)
[rank6]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank6]:     torch.cuda.set_device(device)
[rank6]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank6]:     torch._C._cuda_setDevice(device)
[rank6]: RuntimeError: CUDA error: invalid device ordinal
[rank6]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank6]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank6]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank4]: Traceback (most recent call last):
[rank4]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank4]:     train()
[rank4]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank4]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank4]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank4]:     obj = dtype(**inputs)
[rank4]:   File "<string>", line 118, in __init__
[rank4]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank4]:     and (self.device.type != "cuda")
[rank4]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank4]:     return self._setup_devices
[rank4]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank4]:     cached = self.fget(obj)
[rank4]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank4]:     torch.cuda.set_device(device)
[rank4]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank4]:     torch._C._cuda_setDevice(device)
[rank4]: RuntimeError: CUDA error: invalid device ordinal
[rank4]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank4]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank4]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank1]:     train()
[rank1]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank1]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank1]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank1]:     obj = dtype(**inputs)
[rank1]:   File "<string>", line 118, in __init__
[rank1]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank1]:     and (self.device.type != "cuda")
[rank1]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank1]:     return self._setup_devices
[rank1]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank1]:     cached = self.fget(obj)
[rank1]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank1]:     torch.cuda.set_device(device)
[rank1]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank1]:     torch._C._cuda_setDevice(device)
[rank1]: RuntimeError: CUDA error: invalid device ordinal
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank7]: Traceback (most recent call last):
[rank7]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank7]:     train()
[rank7]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank7]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank7]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank7]:     obj = dtype(**inputs)
[rank7]:   File "<string>", line 118, in __init__
[rank7]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank7]:     and (self.device.type != "cuda")
[rank7]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank7]:     return self._setup_devices
[rank7]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank7]:     cached = self.fget(obj)
[rank7]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank7]:     torch.cuda.set_device(device)
[rank7]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank7]:     torch._C._cuda_setDevice(device)
[rank7]: RuntimeError: CUDA error: invalid device ordinal
[rank7]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank7]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank7]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank3]: Traceback (most recent call last):
[rank3]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank3]:     train()
[rank3]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank3]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank3]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank3]:     obj = dtype(**inputs)
[rank3]:   File "<string>", line 118, in __init__
[rank3]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank3]:     and (self.device.type != "cuda")
[rank3]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank3]:     return self._setup_devices
[rank3]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank3]:     cached = self.fget(obj)
[rank3]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank3]:     torch.cuda.set_device(device)
[rank3]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank3]:     torch._C._cuda_setDevice(device)
[rank3]: RuntimeError: CUDA error: invalid device ordinal
[rank3]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank3]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank3]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank5]: Traceback (most recent call last):
[rank5]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank5]:     train()
[rank5]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank5]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank5]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank5]:     obj = dtype(**inputs)
[rank5]:   File "<string>", line 118, in __init__
[rank5]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank5]:     and (self.device.type != "cuda")
[rank5]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank5]:     return self._setup_devices
[rank5]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank5]:     cached = self.fget(obj)
[rank5]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank5]:     torch.cuda.set_device(device)
[rank5]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank5]:     torch._C._cuda_setDevice(device)
[rank5]: RuntimeError: CUDA error: invalid device ordinal
[rank5]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank5]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank5]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank2]: Traceback (most recent call last):
[rank2]:   File "/mnt/task_runtime/RLHF-V/muffin/./muffin/train/train_mem_muffin.py", line 13, in <module>
[rank2]:     train()
[rank2]:   File "/mnt/task_runtime/RLHF-V/muffin/muffin/train/train_muffin.py", line 452, in train
[rank2]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank2]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
[rank2]:     obj = dtype(**inputs)
[rank2]:   File "<string>", line 118, in __init__
[rank2]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1227, in __post_init__
[rank2]:     and (self.device.type != "cuda")
[rank2]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1662, in device
[rank2]:     return self._setup_devices
[rank2]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
[rank2]:     cached = self.fget(obj)
[rank2]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/transformers/training_args.py", line 1652, in _setup_devices
[rank2]:     torch.cuda.set_device(device)
[rank2]:   File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
[rank2]:     torch._C._cuda_setDevice(device)
[rank2]: RuntimeError: CUDA error: invalid device ordinal
[rank2]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank2]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank2]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

W0430 23:50:38.337000 134467772659520 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 347345 closing signal SIGTERM
E0430 23:50:38.551000 134467772659520 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 347346) of binary: /miniconda/envs/muffin/bin/python
Traceback (most recent call last):
  File "/miniconda/envs/muffin/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.3.0', 'console_scripts', 'torchrun')())
  File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/miniconda/envs/muffin/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./muffin/train/train_mem_muffin.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 347347)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 347348)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 347349)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 347350)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 347351)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 347352)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-30_23:50:38
  host      : local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 347346)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html`

**Comment by yiranyyu** [comment]
Can you give the output of `nvidia-smi` command and the env variable `CUDA_VISIBLE_DEVICES` to help us understand the problem?
