### ISSUE TITLE
γ参数设置问题，原文建议是5，某一版提交后变成1.1了，这是因为有什么区别吗

### ISSUE THREAD

**Issue by Stubborn-one** [RLHF-V/RLHF-V#18]
https://github.com/RLHF-V/RLHF-V/commit/7bea6198432e431f13cec5b03cb8ecf0f653d302
是因为数据集不一样了？
原文是1.4k的后来是5k+

**Comment by yiranyyu** [comment]
你好，感谢关注！

我们发现 1.1 的权重能够更稳定训练从而适合更广泛的训练环境，所以在 readme 中进行了更新。参数的选择可以根据训练使用的数据和训练情况（比如训练是否稳定）进行调整。
