### ISSUE TITLE
eval_muffin_inference_logp.sh this script doesnt seem to be present

### ISSUE THREAD

**Issue by findalexli** [RLHF-V/RLHF-V#2]
Hello there, 

great inspring work! Just looking for this script but could not seem to find this

**Comment by Haoye17** [comment]
Hello! Thanks for your interest in our work~ 

Sorry for the delay in merging the `eval_muffin_inference_logp.sh` file into the main branch. We have now updated the Muffin repository and it can be found [here](https://github.com/thunlp/Muffin/blob/main/script/eval/eval_muffin_inference_logp.sh). You can pull the latest version of the Muffin repo, and the file is now in the same location as mentioned in the readme, which is at `Muffin/script/eval/eval_muffin_inference_logp.sh`.

If you have any more questions or concerns in the future, please do not hesitate to ask us!

**Comment by findalexli** [comment]
Thank you!
