### ISSUE TITLE
请问一下，使用了什么llm?

### ISSUE THREAD

**Issue by dreaming12580** [RLHF-V/RLHF-V#20]
在论文里看到的是 使用13B Vicuna v1.0 ， 但是看代码好像使用的是facebook/opt-125m,   在train里面好像也没有特别指出使用vicuna, 请问一下，使用了什么llm?

**Comment by yiranyyu** [comment]
* We use Vicuna to build the base model Muffin as introduced in the corresponding paper https://arxiv.org/pdf/2310.00653 
* The `Facebook/opt-125m` is a legacy option which will not be used during inference or training.

**Comment by dreaming12580** [comment]
thanks for reply,   got it
