### ISSUE TITLE
waiting for the training code files

### ISSUE THREAD

**Issue by nanamma** [RLHF-V/RLHF-V#25]
such as `./script/train/run_RLHFV.sh` and python files related to it

**Comment by Haoye17** [comment]
Hi @nanamma, thank you for your interest~
The training script can be found in the [Muffin repo](https://github.com/thunlp/Muffin/blob/main/script/train/run_RLHFV.sh), you can follow the instructions [here](https://github.com/RLHF-V/RLHF-V?tab=readme-ov-file#rlhf-v-training) to reproduce the training~
If there are further questions, we are willing to help!

**Comment by nanamma** [comment]
ok. thanks!
