### ISSUE TITLE
Curves of "rewards_train/chosen"

### ISSUE THREAD

**Issue by davidluciolu** [RLHF-V/RLHF-V#26]
Hello! Thanks for your work!

I tried your DPO framework on LLaVA-1.5-7B with my own preference data. I found it weird that the `rewards_train/chosen` first rises then continues to decrease when training. Intuitively, optimizing DPO target **maximizes** the rewards of the **chosen** and minimizes the rewards of the rejected. 

Here shows my curves of "rewards_train/chosen" under different parameter settings.

![image](https://github.com/user-attachments/assets/c913dec7-bb3d-4998-8afa-df958fe85c8a)

The curves of `margins` are shown below and it seems they go well.

![image](https://github.com/user-attachments/assets/3b5df6a9-1c57-4220-9317-2c99e25eee02)

Do your `rewards_train/chosen` decreases when training? I would be appreciated if you can help me find out possible mistakes, either the training process or my understanding of the DPO target.

Thanks a lot!

**Comment by Haoye17** [comment]
Hi @davidluciolu! Thank you for your interest in our work~

The decrease in chosen rewards is a good question in DPO training. As explained by the original author of DPO, the DPO loss function maximizes the **margin** between the chosen reward and the rejected reward, so it may not directly encourage the increase of the chosen reward. In our training process, we also encounter that the chosen rewards decrease. You can find more explanation in this [issue](https://github.com/eric-mitchell/direct-preference-optimization/issues/32#issuecomment-1674253465).

If there are further questions, we are willing to help~

**Comment by davidluciolu** [comment]
Thanks for your reply!
