### ISSUE TITLE
Any plans to release the MHumanEval benchmark?

### ISSUE THREAD

**Issue by Molly-3000** [RLHF-V/RLHF-V#27]
Awesome work! 

Are there any plans to release the MHumanEval benchmark mentioned in the paper? @yiranyyu

**Comment by Haoye17** [comment]
Hi @Molly-3000, thank you for your interest in our work!

The MHumanEval data contains the whole MMHal Bench data and 50 items in the Object HalBench, we've uploaded the 50 items in Object HalBench [here](https://github.com/RLHF-V/RLHF-V/blob/main/eval/data/obj_halbench_mhumaneval_data_with_image.jsonl), and the MMHal Bench can be downloaded [here](https://drive.google.com/file/d/1mQyAbeGgRyiVV6qjVkUI1uY_g9E-bDTH/view).
