### ISSUE TITLE
Using a different model

### ISSUE THREAD

**Issue by DanyalMaq** [RLHF-V/RLHF-V#28]
Is it possible to use a different model in your framework? If so, could you provide some guidance on how one could go about doing it?

**Comment by Haoye17** [comment]
Hi @DanyalMaq ,

Thank you for your interest! Our framework can be applied to other models. To do so, here are some key parts you need to reimplement:
1. Data preprocessing function. Each model has its own data preprocessing procedure to convert raw data into an understandable format. So, you need to apply the model-specific data preprocessing function to reformat the input data.
2. Model architecture. Replace the model architecture with the model you want to use.
3. Inference_logp function. You also need to reimplement the inference logp code to generate model-specific logp values for DPO training. 
4. Trainer and training main script. Modify the trainer and main script to correctly load the model and do training.
