### ISSUE TITLE
the dataset link returns `404`

### ISSUE THREAD

**Issue by linhaojia13** [RLHF-V/RLHF-V#5]
https://huggingface.co/datasets/HaoyeZhang/RLHF-V-Hall_v0/tree/main
When will this dataset be available?

**Comment by Haoye17** [comment]
Hi @linhaojia13 ! Sorry for the inconvenience. 
We reformulated our dataset page these days, and now it is available again~ The new dataset page only contains data in jsonline format to make it easy for preview. If you are seeking the TSV files, you can download them from this [link](https://drive.google.com/drive/folders/1iJ9FvI2ENK9xjN1nAFMgyB5zSTTL1BE6?usp=drive_link)~

**Comment by linhaojia13** [comment]
Thank you very much!
