### ISSUE TITLE
Missing Data (tsv files)

### ISSUE THREAD

**Issue by jacklishufan** [RLHF-V/RLHF-V#6]
"For training simplicity, we generate the logp values based on [RLHF-V_SFT-13B](https://huggingface.co/Yirany/RLHF-V_v0_SFT/tree/main) model and provide it in our dataset in advance."

However I did not find data in the dataset link. There is only one jsonl file. 
How can I convert it to tsv? Because when I tried to generate logp myself, I encountered 
` No such file or directory: './data/RLHF-V-Dataset/RLHF-V-Dataset-1401.tsv'`

**Comment by Haoye17** [comment]
Hi @jacklishufan ! Sorry for the inconvenience. We reformulated our dataset page these days and reuploaded the TSV files in [Google Drive](https://drive.google.com/drive/folders/1iJ9FvI2ENK9xjN1nAFMgyB5zSTTL1BE6?usp=drive_link). You can download it from the Google Drive link now!

**Comment by jacklishufan** [comment]
Hi I do not have access to google drive. It seems that it is not shared with public

**Comment by Haoye17** [comment]
Oh, very sorry for that! Here is the updated [link](https://drive.google.com/drive/folders/1iJ9FvI2ENK9xjN1nAFMgyB5zSTTL1BE6?usp=sharing).
