### ISSUE TITLE
About model size

### ISSUE THREAD

**Issue by yfzhang114** [RLHF-V/RLHF-V#9]
I hope this message finds you well. I am writing to you regarding your GitHub repository and, in particular, the models used in your recent paper. I have noticed that the models mentioned, such as the 13B Vicuna v1.0 and BEit3, differ in architecture from LLaVA-1.5.

In the interest of a fair comparison, I am interested in training a 7B model to align with LLaVA-1.5. However, I couldn't find explicit instructions or commands in your repository on how to train a 7B model. I understand that model size can significantly impact results, and I want to ensure a fair evaluation.

Could you kindly provide guidance or the necessary commands to train a 7B model using your repository? I appreciate your expertise and assistance in making the model comparison as unbiased as possible.

**Comment by yiranyyu** [comment]
Thank you for your interest. To make it clear, as we wrote in the paper, we compared our model with LLaVA 1.5 (**Vicuna 1.5 13B**) which has more advanced language model.

To train a 7B model, you have to update the code related to the [chat templates](https://github.com/thunlp/Muffin/blob/5d32ea69eebf1914cf9e7d3d12a85ba56f3ae9ad/muffin/train/train_utils.py#L262) and possibly write your own [model](https://github.com/thunlp/Muffin/blob/5d32ea69eebf1914cf9e7d3d12a85ba56f3ae9ad/muffin/model/muffin.py#L141). We are also planning to release a 7B model, hope it will be helpful to you.
